# see https://docs.github.com/en/actions
name: 'Sync data to juejin.com'

on: push

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - run: npm install

      - name: Sync
        uses: ./
        with:
          email: ${{ secrets.JUEJIN_EMAIL }}
          password: ${{ secrets.JUEJIN_PASSWORD }}
