# see https://docs.github.com/en/actions
name: 'Sync data to juejin.com'

on: push

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          # # Set always-auth in npmrc
          # always-auth: false # optional, default is false
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 16.x

      - name: Install
        # NOTE: this pins the action to a specific commit sha for security
        # reasons but you can also use a version tag if desired. For example:
        # ianwalter/puppeteer-container@v4.0.0
        uses: ianwalter/puppeteer-container@acc52cd2334ad9eaf6e1974562d263e0a711b7e8
        with:
          args: pnpm i

      - name: Sync
        uses: ./
        with:
          email: ${{ secrets.JUEJIN_EMAIL }}
          password: ${{ secrets.JUEJIN_PASSWORD }}
